[[redirects]]
from = "/i/:id"
to = "/.netlify/images?url=/u/:id"
status = 200

[[redirects]]
from = "/i/:id/:width"
to = "/.netlify/images?url=/u/:id&w=:width"
status = 200

[[redirects]]
from = "/i/:id/:width/:height"
to = "/.netlify/images?url=/u/:id&w=:width&h=:height"
status = 200

[[redirects]]
from = "/i/:id/:width/:height/:fit"
to = "/.netlify/images?url=/u/:id&w=:width&h=:height&fit=:fit"
status = 200

[[redirects]]
from = "/i/:id/:width/:height/:fit/:quality"
to = "/.netlify/images?url=/u/:id&w=:width&h=:height&fit=:fit&q=:quality"
status = 200

[[redirects]]
from = "/i/:id/:width/:height/:fit/:quality/:format"
to = "/.netlify/images?url=/u/:id&w=:width&h=:height&fit=:fit&q=:quality&fm=:format"
status = 200
